---

trigger:
  - main
jobs:
  - job: BuildBackage
    displayName: build sdk package
    timeoutInMinutes: 5
    pool:
      name: 'Azure Pipelines'
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'sdk'
