---
trigger: 
  - master

jobs:
  - job: "first-job"
    displayName: "agentjob"
    pool:
      name: default
      vmImage: ubuntu-latest
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: src/NopCommercs.sln
  
  - job: "second-job"
    displayName: "agent"
    pool:
      name: hema
      vmImage: ubuntu-latest
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          publishWebProjects: true

    