---
trigger: 
  - master

jobs:
  - job: "first_job"
    displayName: "docker image"
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-latest
    steps:
     - task: Docker@2
       inputs:
         containerRegistry: 'Docker Hub'
         repository: 'hema789/nop'
         command: 'buildAndPush'
         Dockerfile: '**/Dockerfile'
         tags: 'latest'