---
trigger:
  - develop
jobs:
  - job: BuildBackage
    displayName: build sdk package
    timeoutInMinutes: 5
    pool:
      name: 'Azure Pipeline'
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      inputs:
       command: 'build'
    - task: DotNetCoreInstaller@1
      inputs:
        packageType: 'sdk'
        version: '2.24.x'
        continueOnError: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'sdk'
