---
trigger: 
  - master

jobs:
  - job: first-job
    displayName: "agent1-job"
    pool:
      name: default
      vmImage: ubuntu-latest
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: src/NopCommercs.sln
  
  - job: second-job
    displayName: "agent2-job"
    pool:
      name: hema
      vmImage: ubuntu-latest
    steps:
      - task: DotNetCoreCLI@2 
        inputs:
          command: 'build'
          publishWebProjects: true

    
