---
trigger:
  - main
jobs:
  - job: BuildBackage
    displayName: build sdk package
    timeoutInMinutes: 5
    pool:
      name: 'Azure Pipelines'
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreInstaller@1
      inputs:
        packageType: 'sdk'
        version: '2.24.x'
        continueOnError: boolean
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'sdk'
